version: 2

updates:
  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
      - 'TooTallNate'
      - 'EndangeredMassa'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /packages/static-build/test/fixtures/angular-v17
    allow:
      - dependency-name: '@angular*'
    groups:
      core:
        patterns:
          - '@angular*'
        update-types:
          - 'minor'

  - schedule:
    interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
      - 'TooTallNate'
      - 'EndangeredMassa'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /packages/static-build/test/fixtures/astro-v4
    allow:
      - dependency-name: 'astro*'
    groups:
      core:
        patterns:
          - 'astro*'
        update-types:
          - 'minor'

  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
      - 'TooTallNate'
      - 'EndangeredMassa'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /packages/static-build/test/fixtures/hydrogen-v2023
    allow:
      - dependency-name: '@remix-run*'
      - dependency-name: '@shopify*'
    groups:
      core:
        patterns:
          - '@remix-run*'
          - '@shopify*'
        update-types:
          - 'minor'

  - schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    reviewers:
      - 'trek'
      - 'TooTallNate'
      - 'EndangeredMassa'
    commit-message:
      prefix: '[framework-fixtures]'
    package-ecosystem: 'npm'
    directory: /packages/static-build/test/fixtures/stencil-v4
    allow:
      - dependency-name: "@stencil/core"
    groups:
      core:
        patterns:
          - "@stencil/core"
        update-types:
          - "minor"
