blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://vercel.com/support/request
    about: Report a bug using the Vercel support form
  - name: Feature Request
    url: https://github.com/vercel/vercel/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/vercel/vercel/discussions/new?category=help
    about: Ask the community for help
