[package]
name = "vercel_python_analysis"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ruff_python_ast = { git = "https://github.com/astral-sh/ruff", rev = "22f240dadf58837f9ac55e5f06d591449f620847" }
ruff_python_parser = { git = "https://github.com/astral-sh/ruff", rev = "22f240dadf58837f9ac55e5f06d591449f620847" }
wit-bindgen.workspace = true

[build-dependencies]
wit-bindgen-rust.workspace = true

[package.metadata.component]
package = "vercel:python-analysis"

[package.metadata.component.target]
path = "wit"
world = "python-analysis"
