# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ananke Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/budparr/gohugo-theme-ananke"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.30.2"

[author]
  name = "Bud Parr"
  homepage = "https://github.com/budparr"
