name: Cron Update Next

on:
  # Allow manual runs
  workflow_dispatch:
  # Run every 4 hours https://crontab.guru/every-4-hours
  schedule:
    - cron: '0 */4 * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # 0 means fetch all commits so we can commit and push in the script below
        with:
          fetch-depth: 0
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Create Pull Request
        uses: actions/github-script@v6
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
        # See https://github.com/actions/github-script#run-a-separate-file-with-an-async-function
        with:
          github-token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          script: |
            const script = require('./utils/update-next.js')
            await script({ github, context })
