name: Inkeep Source Sync

on:
  push:
    branches:
      - main
    paths:
      - 'examples/docusaurus/**'
      - 'examples/astro/**'
    
jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            site:
              - 'examples/docusaurus/**'
            docs:
              - 'examples/astro/**'

      - name: Sync Site Source 
        if: steps.changes.outputs.site == 'true'
        uses: inkeep/pr-commenter-action@v5
        with:
          api-key: ${{ secrets.INKEEP_API_KEY }}
          source-id: 'clohl0lk20000s601g2siksub'

      - name: Sync Docs Source 
        if: steps.changes.outputs.docs == 'true'
        uses: inkeep/pr-commenter-action@v5
        with:
          api-key: ${{ secrets.INKEEP_API_KEY }}
          source-id: 'clohg84p70000s6010tuqnpb9'
          

        