name: Publish

on:
  push:
    branches:
      - main
    tags:
      - '!*'

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Release
        id: check-release
        run: |
          tag="$(git describe --tags --exact-match 2> /dev/null || :)"
          if [[ -z "$tag" ]];
            then
              echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
            else
              echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
          fi
      - name: Setup Go
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        uses: actions/setup-go@v3
        with:
          go-version: '1.13.15'
      - name: Setup Node
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install npm@9
        run: npm i -g npm@9
      - name: install pnpm@7.31.0
        run: npm i -g pnpm@7.31.0
      - name: Install
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        run: pnpm install
      - name: Build
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        run: pnpm build
        env:
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Publish
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        run: pnpm publish-from-github
        env:
          NPM_CONFIG_PROVENANCE: 'true'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Trigger Update
        if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          script: |
            const script = require('./utils/trigger-update-workflow.js')
            await script({ github, context })
