name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA to release the CLI from'
        required: true
      dryRun:
        description: 'Whether to run the publish process in dry run mode.'
        type: boolean
        required: true
        default: true

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.event_name == 'push'
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}

      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install npm@9
        run: npm i -g npm@9

      - name: install pnpm@8.3.1
        run: npm i -g pnpm@8.3.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          NPM_CONFIG_PROVENANCE: 'true'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Trigger Update (if a Publish Happened)
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          script: |
            const script = require('./utils/trigger-update-workflow.js')
            await script({ github, context })

      - name: Set latest Release to `vercel` (if a Publish Happened)
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          script: |
            const script = require('./utils/update-latest-release.js')
            await script({ github, context })
  manual-cli-release:
    if: github.event_name == 'workflow_dispatch'
    name: Manual CLI Release ${{github.event.inputs.dryRun == 'true' && '(--dry-run)' || ''}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          ref: ${{ github.event.inputs.commit }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install npm@9
        run: npm i -g npm@9

      - name: install pnpm@8.3.1
        run: npm i -g pnpm@8.3.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Version CLI, publish and comment on PR
        run: |
          cd packages/cli &&
          VERSION=$(node -p "require('./package.json').version")-canary.${{ github.event.inputs.commit }} &&
          pnpm version $VERSION --no-git-tag-version &&
          pnpm publish --access public --tag canary ${{ github.event.inputs.dryRun == 'true' && '--dry-run' || '' }} --no-git-checks &&
          echo "ðŸš€ Published canary version, install via: \`pnpm add vercel@$VERSION\`"

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          NPM_CONFIG_PROVENANCE: 'true'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  summary:
    name: Summary (release)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - release
    steps:
      - name: Check All
        run: echo OK
