name: Lint

on:
  pull_request:

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  NODE_VERSION: '18'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  enforce-changeset:
    name: Enforce Changeset
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
      - run: git fetch origin ${{ github.event.pull_request.head.sha }}:pr-${{ github.event.pull_request.number }}
      - run: git checkout pr-${{ github.event.pull_request.number }}
      - name: install pnpm@8.3.1
        run: npm i -g pnpm@8.3.1
      - run: pnpm install
      # Enforce a changeset file to be present
      - run: pnpm exec changeset status --since=main

  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install pnpm@8.3.1
        run: npm i -g pnpm@8.3.1
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run prettier-check
      - run: pnpm run build
      - run: pnpm run type-check
      - name: Ensure clean git workspace
        run: git diff --name-only --exit-code

  summary:
    name: Summary (lint)
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs:
      - enforce-changeset
      - lint
    steps:
      - name: Check All
        run: |-
          for status in ${{ join(needs.*.result, ' ') }}
          do
            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
            then
              echo "Some checks failed"
              exit 1
            fi
          done
