name: Unit

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: Unit
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set remote env
        run: |
            echo "TURBO_REMOTE_ONLY=true" >> $GITHUB_ENV
            echo "TURBO_TEAM=vercel" >> $GITHUB_ENV
            echo "TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13.15'
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
      - run: echo "${{ env.TURBO_REMOTE_ONLY }}"
      - run: node -p "process.env.TURBO_REMOTE_ONLY"
      - run: yarn install --network-timeout 1000000 --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run lint once
      - run: yarn run test-unit
      - run: yarn workspace vercel run coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run coverage once
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
